DELETE FROM FactHoliday
DELETE FROM Address
DELETE FROM Salaries
DELETE FROM PretendingEmployees
DELETE FROM PlanHoliday
DELETE FROM Holiday
DELETE FROM StuffDepartment
DELETE FROM Vacancy
DELETE FROM Posts
DELETE FROM Departments
DELETE FROM Employees