DROP TABLE FactHoliday
DROP TABLE Address 
DROP TABLE Salaries
DROP TABLE PretendingEmployees
DROP TABLE PlanHoliday
DROP TABLE Holiday
DROP TABLE StuffDepartment
DROP TABLE Vacancy
DROP TABLE Posts
DROP TABLE Departments
DROP TABLE Employees